### ISSUE TITLE
product_code应该填什么

### ISSUE THREAD

**Issue by hUangDDD** [lawrence-peng/alipay-node#2]
如题，
支付宝的文档里没看到这个参数

**Comment by lawrence-peng** [comment]
APP支付 product_code 填 `'QUICK_MSECURITY_PAY'`
[APP支付请求参数](https://docs.open.alipay.com/204/105465/)
手机网站支付 product_code 填 `'QUICK_WAP_WAY'`
 [手机网站支付请求参数](https://docs.open.alipay.com/203/107090/)
还有其它方式 ，请参考官方文档

**Comment by hUangDDD** [comment]
thx
